version: "2"

services:
  mysql:  
      networks:
        default:
          aliases:
            - recipe
      image: mysql:5.7
      ports:
        - "3315:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=fixins
        - MYSQL_DATABASE=recipe