version: "2"

networks: 
  default:
    external:
      name: recipe

services:
  mysql:  
    networks:
      default:
        aliases:
          - recipe_mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=fixins
      - MYSQL_DATABASE=recipe
  golang_backend:
    networks:
      default:
        aliases:
          - recipe_go
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "80:7000"
